wasimreja/book-finder

index.html, main.js
Hi, this change enables a user to search books by pressing enter and it removes focus from the input bar upon search.
- [✔️] I am making a proper pull request, not spam.
- [✔️] I've checked the issue list before deciding what to submit.
This PR solves issue #1
=> fix: pressing enter searches for book and removes focus from search bar

index.html, main.js
Fixing Issue #11 - Read Button 
New action to "read button" #11
=> Fix read button

style.css
Currently, the search results look connected. This separates them by increasing the space between them.
=> Seperate search results

main.js, style.css
add author name of book below the title
(Add here)
=> add author name of book below the title

.vscode/settings.json, index.html
- I have added header sematic HTML tag as mentioned in description. Please check my PR.
=> sematic header tag added

index.html
- I have added `<main>` tag and `<section>` for results.
(Add here)
=> main and section tag added

main.js
#hacktoberfest 
#44 solution
I have solved the issue
=> bug fixed for book not found

index.html, main.js, style.css
=> Improved UI for book list

main.js
Fixed the bug Clearing input field after search
#57 
#57
=> Fixed the bug Clearing input field after search

main.js
This PR is in reference to the issue #66 
For undefined content fetched from the API, it will show an appropriate substitute text as in the screenshot
=> fixed undefined bug

index.html, style.css
changed the background of home page
issue #77
=> changed the background of home page

index.html, main.js, style.css
Added Voice Method so that that user can listen the information about book
#76 issue resolved
@wasimreja  please merge now for hacktoberfest as said by you in this [pr](https://github.com/wasimreja/book-finder/pull/76)
=> Added Voice Method

style.css
Added hover property and transition to the search button
issue #89 
https://user-images.githubusercontent.com/94471189/194570606-7af499c5-08df-4806-9c9e-3445783b488d.mp4
=> Added hover property and transition to the search button

style.css
Fixed the issue of overlapping of the navbar when scroll down.
Navbar Overlapping Issue #97
=> Fixed Navbar Overlapping Issue #97

main.js
Form is no longer doing a request when input is empty and you click enter or click on search icon
NA
=> fix issue 109: resolved unnecessary request when input is empty

main.js, style.css
Improved the UI by adding a read more button to the description of the books to limit the amount of text shown to the user at once.
The search results show the first 100 characters of the description to begin with. When the user clicks on the 'Read More' button, the entire description is shown. When the entire description is being shown, the user can click on the 'Read Less' button to close the long description.
If the description is not available, the button is not shown.
This enhancement is related to issue #106 which was opened by me.
1. When a description is not available:
2. Initial Search Result:
3. Extended Search Result:
=> Search Result Card UI Redesign #106

index.html
fixed the redirect to homepage by clicking the logo(changed the href pointer to "index.html")
- [ yes] I am making a proper pull request, not spam.
- [ yes] I've checked the issue list before deciding what to submit.
(Add here)
=> fixed issue of redirecting to homepage by clicking the logo

main.js
Reverts wasimreja/book-finder#124
=> Revert "Improve variable naming"

index.html
(The whirly loading animation was not working. Now it's been fixed)
- [*] I am making a proper pull request, not spam.
- [*] I've checked the issue list before deciding what to submit.
(Add here)
=> fixed Loading issue after first search

index.html, main.js
this closes #148 
https://user-images.githubusercontent.com/96380323/194864406-cda2407e-1353-4725-912c-01e21b57c361.mp4
=> added animation to book cards

index.html
Fix the issue of delay in card animation #153
=> Fixed issue delay in card animation #153

index.html, main.js
Now theme will remain persisted on page refresh.
https://github.com/wasimreja/book-finder/issues/173
[screen-capture (2).webm](https://user-images.githubusercontent.com/45123508/195409598-7659f626-7a72-4340-b40b-d6f7762f3ac2.webm)
=> Feature: persisting theme via localStorage

style.css
Scroll bar style updated in standard of current theme for both light and dark mode
Issue: #174 
Light:
Dark:
=> scroller style updated

index.html, style.css
Add a hover effect on the search icon and off the autocomplete function
https://github.com/wasimreja/book-finder/issues/106
https://github.com/wasimreja/book-finder/issues/79
(Add here)
=> Hacktoberfest

about.html, index.html, style.css
Feature : Add about page [fixes #191]
fixes #191 
(Add here)
=> Feature : Add about page [fixes #191]

.vscode/settings.json, index.html, style.css
The description in the about us page was not visible during dark mode it was black color text.
#196
=> Added proper styling for description 

about.html, style.css
I made the about page responsible.
fixes #200
=> make about page responsible

about.html, index.html, main.js, style.css
Added Hamburger menu For small screen devices.
✔️I am making a proper pull request, not spam.
✔️ I've checked the issue list before deciding what to submit.
Improve navbar UI for small screens #194
https://github.com/wasimreja/book-finder/issues/194
=> Added Hamburger Menu for Small Screen Devices

.vscode/settings.json, about.html, style.css
Footer has been added to about us page and changes have been made to make it responsive in small screens .
=> adding footer to about us page

style.css
Added navbar link hover effect. 
(Add here)
=> feat: add navbar hover effect

style.css
Enhance dark theme color palette. 
(Add here)
=> feat: enhance dark theme color palette

style.css
Changed search bar color for dark theme.
(Add here)
=> feat: change search bar color

style.css
Changed result card color for dark theme.
(Add here)
=> feat: change result card color

index.html
Accessibility fixes and improvements
=> Changes to accommodate Lighthouse audit

main.js
Commented out the console.logs that would possibly appear when a particular event happens so that the console remains clear and nothing appears on the console.
=> Commented out the extra console.logs from main.js 

README.md, contributors.json
Resolved issue #244 
(Add here)
=> Added contributors.json 

main.js, style.css
(I have used the icon image to toggle the color of the error message while changing the theme to slve this issue.)
(The issue is now resolved.)
https://user-images.githubusercontent.com/77235824/218965228-bb644924-dce7-43e8-942f-25b5c45e106a.mp4
=> Made chnages to fix the error message visibility in dark theme

style.css
The Footer position not in right place #239 is fixed !
- [ ✓] I am making a proper pull request, not spam.
- [ ✓] I've checked the issue list before deciding what to submit.
Please review the PR and merge the changes!
Thank you!
=> Footer position in home page is fixed

main.js
added an alert box with proper guideline when nothing is entered in search box.
(Add here)
=> added alert when nothing is entered in search box

style.css
Overlapping problem fixed by giving bottom margin.
- [1 ] I am making a proper pull request, not spam.
- [ 1] I've checked the issue list before deciding what to submit.
(Add here)
=> Whirly loader overlapping problem

about.html, index.html, style.css
=> #250 Feature:implemented a footer

style.css
There is a problem of overlapping in the footer page which is solved using css.
closes: Issue no #263
=> Footer overlapping solved

about.html, contributors.css, contributors.html, contributors.json, index.html
Created a contributors list page
(Add here)
=> Added Contributors Page

about.html, index.html, style.css
=> resolved footer overlap

about.html, index.html, style.css
Reverts wasimreja/book-finder#281
=> Revert "resolved footer overlap"

about.html, contributors.css, contributors.html, index.html, style.css
=> enhanced hamburger and navbar

about.css, about.html, style.css
added some changes in about us page
#264
=> About enhance

js/main.js
Myself sayandip paul participating under jwoc .
I fixed the issue recntly.
kindly check this.
- [. ] I am making a proper pull request, not spam.
- [. ] I've checked the issue list before deciding what to submit.
I have changed the main.js file
(Add here)
=> Fixed the issue Error message is not readable in light theme.

about.html, index.html
Fixed the multiple body tag issue.
(Add here)
=> Fixed body tags

about.html, contributors.html, css/style.css, index.html
Added Logo within navbar beside the brand title
(Add here)
=> Added logo on nav

about.html, css/about.css
made the page responsive and updated it with some new things
#315
=> about us page updated

css/style.css, index.html, js/main.js, js/pagination.js
=> designed pagination

about.html, contact.html, contributors.html, css/feature.css, features.html, index.html
=> revamped feature page, and minor changes

about.html, contact.html, contributors.html, css/style.css, css/translate.css, faq.html, features.html, index.html, js/translate.js
Added language translator
Closes #338 
I guess difficulty level for this pr should be increased...
=> Language translator

index.html, js/main.js, js/pagination.js
Added Pagination Functionality in most simple way
(Add here)
=> Added Pagination

contributors.json
updated contributors list
(Add here)
=> Updated list

css/error.css
Fixed responsiveness issues for 100% screen size.
(Add here)
=> Fixed Responsiveness

css/error.css
Reverts wasimreja/book-finder#355
=> Revert "Fixed Responsiveness"

.vscode/settings.json, contact.html
=> Fixed the email bug

contact.html, css/contact.css, css/style.css
Fixed the bugs of Contact Page
(Add here)
=> Fixing Contact Page
